using Microsoft.EntityFrameworkCore;
using MovieTicketApi.Helper;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieTicketApi.Entities
{
    [PrimaryKey("Id")]
    public class Booking
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]   //This will make sure it will be an identity column, so will be autogenerated
        public int Id { get; set; }
        [UserRole]
        public required string DoneBy { get; set; }
        [ForeignKey("UserMaster")]
        public int? UserId { get; set; }
        [ForeignKey("MovieMaster")]
        public int MovieId { get; set; }
        [ForeignKey("TheatreScreen")]
        public int ScreenId { get; set; }
        public int Row { get; set; }
        public string SeatNo { get; set; }
        public DateTime ShowTime { get; set; }


        public virtual UserMaster UserMaster { get; set; }    //This will be used for FK crud operation
        public virtual MovieMaster MovieMaster { get; set; }    //This will be used for FK crud operation
        public virtual TheatreScreen TheatreScreen { get; set; }    //This will be used for FK crud operation
    }
}
