using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieTicketApi.Entities
{
    [PrimaryKey("Id")]
    public class MovieListing
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]   //This will make sure it will be an identity column, so will be autogenerated
        public int Id { get; set; }
        [ForeignKey("MovieMaster")]
        public int MovieId { get; set; }
        [ForeignKey("TheatreScreen")]
        public int ScreenId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; } //Will be calculated as per movie runtime
        public bool IsActive { get; set; }


        public virtual MovieMaster MovieMaster { get; set; }        //This will be used for FK crud operation
        public virtual TheatreScreen TheatreScreen { get; set; }    //This will be used for FK crud operation
    }
}
