using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieTicketApi.Entities
{
    [PrimaryKey("Id")]
    public class MovieListing
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]   //This will make sure it will be an identity column, so will be autogenerated
        public int Id { get; set; }
        [ForeignKey("TheatreScreen")]
        public int ScreenId { get; set; }


        public virtual TheatreScreen TheatreScreen { get; set; }    //This will be used for FK crud operation
    }
}
