using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieTicketApi.Entities
{
    [PrimaryKey("Id")]
    public class UserMaster
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]   //This will make sure it will be an identity column, so will be autogenerated
        public int Id { get; set; }
        public string Name { get; set; }
        public required string Email { get; set; }
        public required string Password { get; set; }
        public string? Location { get; set; } = string.Empty;
    }
}
